# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autenticador.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61utenticador.proto\x12\x0c\x61utenticador\"\xb2\x01\n\x0cHelloRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0flugarNacimiento\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1a\n\ranoNacimiento\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x17\n\ncontrasena\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x07\n\x05_nameB\x12\n\x10_lugarNacimientoB\x10\n\x0e_anoNacimientoB\r\n\x0b_contrasena\"N\n\nHelloReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06status\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\n\n\x08_messageB\t\n\x07_status2T\n\x0c\x41utenticador\x12\x44\n\nautenticar\x12\x1a.autenticador.HelloRequest\x1a\x18.autenticador.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autenticador_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=37
  _globals['_HELLOREQUEST']._serialized_end=215
  _globals['_HELLOREPLY']._serialized_start=217
  _globals['_HELLOREPLY']._serialized_end=295
  _globals['_AUTENTICADOR']._serialized_start=297
  _globals['_AUTENTICADOR']._serialized_end=381
# @@protoc_insertion_point(module_scope)
